#app server settings
server:
  port: 9999
  context-path: /melon

spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: solstice
    port: 6379
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 3000
    #sentinel:
     # master: #main node name
     # nodes:  #all nodes' name separated by comma,host:port


#  devtools:
#    restart:
#      enabled: true
  datasource:
    name: repositpry
    url: jdbc:mysql://127.0.0.1:3306/melon?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: solstice
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  application:
    name: melon-api

#  dubbo:
#      provider:
#        service:
#          version: 1.0.0
#      basePackages: com.solstice.melon.service
#      registry:
#        id: melon-dubbo
#        address: zookeeper://127.0.0.1:2181
#      application:
#        id: dubbo-provider-melon
#        name: dubbo-provider-melon
#      protocal:
#        id: dubbo
#        name: dubbo
#        port: 20880

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.solstice.melon.domain
  typeEnumsPackage: com.solstice.melon.enums
  global-config:
      #刷新mapper 调试神器
      refresh-mapper: true
      #驼峰下划线转换
      db-column-underline: true
#  type-handlers-package: com.solstice.melon.typeHandlers

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level: warn